Fix  pip install on non windows machine
Previously, the README contained characters encoded with
Windows-1252 (0.73). On non windows machines, this breaks pip install
with a UnicodeDecodeError:

```
pip install git+https://github.com/Petro-Logistics/petro-api-python
Collecting git+https://github.com/Petro-Logistics/petro-api-python (from -r requirements.txt (line 43))
  Cloning https://github.com/Petro-Logistics/petro-api-python to /private/var/folders/2m/jp5gz74170l1vk3231j78nqh0000gn/T/pip-req-build-yhbjlcrd
  Running command git clone --filter=blob:none --quiet https://github.com/Petro-Logistics/petro-api-python /private/var/folders/2m/jp5gz74170l1vk3231j78nqh0000gn/T/pip-req-build-yhbjlcrd
  Resolved https://github.com/Petro-Logistics/petro-api-python to commit 94da517144a499f797de4820ec6eef393cedc201
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/2m/jp5gz74170l1vk3231j78nqh0000gn/T/pip-req-build-yhbjlcrd/setup.py", line 12, in <module>
          README = readme.read()
        File "/Users/Neil/.pyenv/versions/3.7.11/lib/python3.7/codecs.py", line 322, in decode
          (result, consumed) = self._buffer_decode(data, self.errors, final)
      UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 986: invalid start byte
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

The non utf-8 characters are for smart quotes. This change replaces
the smart quotes with regular straight quotes